config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'top#index'

  # ログイン
  get 'login', to: "auth#new", as: "login"
  delete 'logout', to: "auth#destroy", as: "logout"
  match "auth/:provider/callback", to: "auth#create", as: "auth_callback", via: %i[get post]
  post 'auth_test', to: "auth#test_create", as: "auth_test"

  # コネクション
  resources :connections, only: %i[create edit], param: :code
  get "connections/:type/:user_code", to: "connections#new", as: :new_connection
  put "connections/:code/approve", to: "connections#approve", as: :approve_connection
  put "connections/:code/reject", to: "connections#reject", as: :reject_connection

  # プロフィール
  scope :profile do
    get "/", to: "profile#show", as: "profile"
    get "edit", to: "profile#edit", as: "edit_profile"
    patch "/", to: "profile#update"
    resource :my_business, only: %i[edit update]
  end

  resources :businesses, only: %i[index show], param: :code
  resources :users, only: %i[show], param: :code
  resources :plans, only: %i[index create]
  resources :payments, only: %i[new create]
  resources :notifications, only: %i[index]
  resources :message_rooms, only: %i[index show]

  # 静的ページ
  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    ids = [BusinessSupplyElement, BusinessDemandElement].map do |klass|
      i_ids = klass.where(industry_id: params[:industry_id]).pluck(:business_id) if params[:industry_id]
      o_ids = klass.where(occupation_id: params[:occupation_id]).pluck(:business_id) if params[:occupation_id]
      i_ids | o_ids
    end.flatten.uniq

    @businesses = Business.published
                          .yield_self { |q| [params[:occupation_id], params[:industry_id]].any?(&:present?) ? q.where(id: ids) : q }
                          .yield_self { |q| user_login? ? q.where.not(id: current_user.business.id) : q }
  end

  def show
   my_business = current_user&.business
   @business = if my_business.present? && my_business.code == params[:code]
     current_user.business
   else
     Business.published.find_by!(code: params[:code])
   end
  end

  class BusinessSearchService
    def initialize(businesses)
      @businesses = businesses
    end

    def search
    end
  end
end

app/views/businesses/index.html.slim
h1 案件一覧

.form.white-box
  = form_tag businesses_path, method: 'get' do
    .form-half
     = select_tag :industry_id, options_for_select({ '業界': nil }.merge(Industry.pluck(:name, :id).to_h), selected: params[:industry_id], class: 'select')
     = select_tag :occupation_id, options_for_select({ '業種': nil }.merge(Occupation.pluck(:name, :id).to_h), selected: params[:occupation_id], class: 'select')
    .form-half
      = text_field_tag :search_text, params[:search_text], placeholder: 'キーワード', class: 'textField'
      = submit_tag '検索する', class: 'button'

main.white-box
  - if @businesses.any?
    ul
      - @businesses.each do |business|
        li
          = link_to business_path(business) do
            .left
              .img-wrap
                - if business.image.present?
                  = image_tag business.image.thumbnail.to_s, class: 'img'
                - else
                  span.img.blank
                / span.user-link
                  / - if business.user.avatar_image.present?
                    / = image_tag business.user.avatar_image.to_s, class: 'user-image'
                  / - else
                    / = content_tag(:span, '', class: 'user-image blank')
                  / = business.user.name
            .right
              h3 = business.title
              p = business.detail
          
  - else
    h3 指定した条件の案件は存在しません

app/views/businesses/show.html.slim
header.white-box
  .heading
    h2 = @business.title
    small
      - if @business.name
        = @business.name
        - if @business.prefecture
          = "（#{@business.prefecture_name}）"
      - else
        - if @business.prefecture
          = @business.prefecture_name

  - if @business.image.present?
    = image_tag @business.image.to_s, class: 'main-image'

  .infos
    = link_to user_path(@business.user), class: 'user-link' do
      - if @business.user.avatar_image.present?
        = image_tag @business.user.avatar_image.to_s, class: 'user-image'
      - else
        span.user-image.blank
      = @business.user.name


    .buttons
      - if user_login?
        - if @business.id == @current_user&.business&.id
          = link_to '編集する', edit_my_business_path, class: 'btn'
        - else
          - if current_user.has_connection?(@business.user)
            span.btn.disabled = 'つながる'
          - else
            = link_to 'つながる', new_connection_path(user_code: @business.user.code, type: :direct), class: 'btn'
          = link_to '紹介する', new_connection_path(user_code: @business.user.code, type: :introduce), class: 'btn'
          / = button_tag 'シェアする', class: 'btn'
      - else
        = link_to 'つながる', login_path, class: 'btn'
        = link_to '紹介する', login_path, class: 'btn'
        

section.white-box
  h3 事業詳細
  p = @business.detail

- if @business.business_demand_elements.any?
  section.white-box
    h3 こんな人紹介してくれませんか？
    ul
      - @business.business_demand_elements.each do |element|
        li
          h4 = element.title
          small.label = element.industry_name
          small.label = element.occupation_name

- if @business.business_supply_elements.any?
  section.white-box
    h3 私たちはこんな人を紹介できます！
    ul
      - @business.business_supply_elements.each do |element|
       li
         h4 = element.title
         small.label = element.industry_name
         small.label = element.occupation_name