config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'top#index'

  # ログイン
  get 'login', to: "auth#new", as: "login"
  delete 'logout', to: "auth#destroy", as: "logout"
  match "auth/:provider/callback", to: "auth#create", as: "auth_callback", via: %i[get post]
  post 'auth_test', to: "auth#test_create", as: "auth_test"

  # コネクション
  resources :connections, only: %i[create edit], param: :code
  get "connections/:type/:user_code", to: "connections#new", as: :new_connection
  put "connections/:code/approve", to: "connections#approve", as: :approve_connection
  put "connections/:code/reject", to: "connections#reject", as: :reject_connection

  # プロフィール
  scope :profile do
    get "/", to: "profile#show", as: "profile"
    get "edit", to: "profile#edit", as: "edit_profile"
    patch "/", to: "profile#update"
    resource :my_business, only: %i[edit update]
  end

  resources :businesses, only: %i[index show], param: :code
  resources :users, only: %i[show], param: :code
  resources :plans, only: %i[index create]
  resources :payments, only: %i[new create]
  resources :notifications, only: %i[index]
  resources :message_rooms, only: %i[index show]

  # 静的ページ
  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :external_credentials
  has_many :user_connections
  has_many :friends, through: :user_connections, foreign_key: :friend_id
  has_many :user_plans
  has_many :plans, through: :user_plans
  has_many :connection_notifications
  has_many :message_room_users
  has_many :message_rooms, through: :message_room_users
  has_many :messages
  has_one :business
  belongs_to :prefecture, required: false

  before_create :reset_code
  after_create :create_business

  validates :name, presence: true
  validates :email, presence: true

  enum status: {
    deleted: 0,
    active: 1
  }

  enum gender: {
    unknown: 0,
    male: 1,
    female: 2
  }

  delegate :name, to: :prefecture, prefix: true, allow_nil: true
  delegate :name, to: :plan, prefix: true
  delegate :list_capacity, to: :plan

  mount_uploader :cover_image, CoverImageUploader
  mount_uploader :avatar_image, AvatarImageUploader

  def has_connection?(user)
    friends.include?(user)
  end

  def full_friend?
    (list_capacity - friends.count) <= 0
  end

  def age
    return unless birthday
    (Date.today.strftime('%Y%m%d').to_i - birthday.strftime('%Y%m%d').to_i) / 10000
  end

  def current_plan
    UserPlan.current(self)
  end
  alias plan current_plan

  def splited_code
    uuid.scan(/(.{4})(.{4})(.{4})(.{4})/)[0].join("-")
  end

  # override
  def to_param
    code
  end

  private

  def reset_code
    self.code = SecureRandom.hex(8).upcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by!(code: params[:code])
  end
end

app/views/users/show.html.slim
header.user-header
  .white-box
    - if @user.cover_image.present?
      = image_tag @user.cover_image.to_s, class: 'cover'
    - else
      .cover.blank
    - if @user.avatar_image.present?
      = image_tag @user.avatar_image.to_s, class: 'avatar'
    - else
      .avatar.blank
    h2.heading =  @user.name
    ul.buttons
      li = link_to '基本データ', user_path(@user), class: 'btn'
      li = content_tag(:span, 'ランキング', class: 'btn disabled')
      li = content_tag(:span, 'リファラル数', class: 'btn disabled')
      li = content_tag(:span, 'つながり数', class: 'btn disabled')
      - if @user == current_user
        - if user_login?
          li = link_to '編集する', edit_profile_path, class: 'btn'
      - else
        li = link_to 'つながる', new_connection_path(user_code: @user.code, type: :direct), class: 'btn'
        li = link_to '紹介する', new_connection_path(user_code: @user.code, type: :introduce), class: 'btn'

section#basic-data
  h3 基本データ
  .box.white-box
    ul
      li 
        label 名前
        span = @user.name
      - if @user.birthday
        li
          label 年齢
          = "#{@user.age}歳"
      - unless @user.unknown?
        li
          label 性別
          = @user.gender

- if @user.detail.present?
  section
    h3 自己紹介
    .box.white-box
      p.text = safe_join(@user.detail.split("\n"),tag(:br))

- if @user.business.published?
  section#business
    h3 事業
    .box.white-box
      = link_to business_path(@user.business) do
        h4 = @user.business.title
        p = @user.business.detail

- if @user.friends.any?
  section#user-link-list
    h3 つながり
    .box.white-box
      ul
        - @user.friends.each do |user|
          li
            = link_to user_path(user), class: 'user-link' do
              - if user.avatar_image.present?
                = image_tag user.avatar_image.to_s, class: 'user-image'
              - else
                span.user-image.blank
              = user.name